# Generated by Django 6.0.3 on 2026-03-21 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_productalias'),
        ('purchases', '0003_alter_purchaseorder_po_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactPriceChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=64)),
                ('changed_at', models.DateTimeField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_difference', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('direction', models.CharField(choices=[('flat', 'Flat'), ('up', 'Up'), ('down', 'Down')], max_length=10)),
                ('accepted_flag', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_price_change_events', to='purchases.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_price_change_events', to='inventory.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_price_change_events', to='inventory.vendor')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
                'indexes': [models.Index(fields=['product'], name='analytics_fpce_product_idx'), models.Index(fields=['vendor'], name='analytics_fpce_vendor_idx'), models.Index(fields=['changed_at'], name='analytics_fpce_changed_idx')],
            },
        ),
        migrations.CreateModel(
            name='FactPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('original_po_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('final_net_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('final_tax_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('final_grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('invoice_net_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('invoice_tax_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('invoice_grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('po_item_count', models.PositiveIntegerField(default=0)),
                ('was_auto_validated', models.BooleanField(default=False)),
                ('was_manually_reconciled', models.BooleanField(default=False)),
                ('has_name_reconciliation', models.BooleanField(default=False)),
                ('has_quantity_reconciliation', models.BooleanField(default=False)),
                ('has_price_reconciliation', models.BooleanField(default=False)),
                ('total_value_variance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quantity_variance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_variance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('po', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_fact', to='purchases.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_purchase_orders', to='inventory.vendor')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at'], name='analytics_fpo_created_idx'), models.Index(fields=['closed_at'], name='analytics_fpo_closed_idx'), models.Index(fields=['vendor'], name='analytics_fpo_vendor_idx'), models.Index(fields=['status'], name='analytics_fpo_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='FactPurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=64)),
                ('product_display_name_snapshot', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('po_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('po_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('po_line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('invoice_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('invoice_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('invoice_line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('accepted_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('accepted_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('accepted_line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('name_reconciled_flag', models.BooleanField(default=False)),
                ('quantity_reconciled_flag', models.BooleanField(default=False)),
                ('price_reconciled_flag', models.BooleanField(default=False)),
                ('quantity_change_type', models.CharField(choices=[('none', 'No Change'), ('shortage_confirmed', 'Shortage Confirmed'), ('full_receipt_confirmed', 'Full Receipt Confirmed'), ('additional_quantity_accepted', 'Additional Quantity Accepted'), ('additional_quantity_rejected', 'Additional Quantity Rejected')], default='none', max_length=40)),
                ('price_change_type', models.CharField(choices=[('none', 'No Change'), ('updated_to_invoice', 'Updated To Invoice Price'), ('kept_old_price', 'Kept Old Price')], default='none', max_length=30)),
                ('quantity_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_price_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('line_total_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_fact_items', to='purchases.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_purchase_order_items', to='inventory.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_purchase_order_items', to='inventory.vendor')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product'], name='analytics_fpoi_product_idx'), models.Index(fields=['vendor'], name='analytics_fpoi_vendor_idx'), models.Index(fields=['created_at'], name='analytics_fpoi_created_idx')],
            },
        ),
    ]
