# Generated by Django 6.0.3 on 2026-03-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factpricechangeevent',
            name='direction',
            field=models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=10),
        ),
        migrations.AlterField(
            model_name='factpurchaseorderitem',
            name='price_change_type',
            field=models.CharField(choices=[('none', 'No Change'), ('price_increase_accepted', 'Price Increase Accepted'), ('price_decrease_accepted', 'Price Decrease Accepted'), ('invoice_price_rejected', 'Invoice Price Rejected')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='factpurchaseorderitem',
            name='quantity_change_type',
            field=models.CharField(choices=[('none', 'No Change'), ('shortage_confirmed', 'Shortage Confirmed'), ('full_quantity_confirmed', 'Full Quantity Confirmed'), ('extra_qty_accepted', 'Extra Quantity Accepted'), ('extra_qty_rejected', 'Extra Quantity Rejected')], default='none', max_length=40),
        ),
    ]
