# Generated by Django 6.0.3 on 2026-03-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='validation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='validation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('invoice_uploaded', 'Invoice Uploaded'), ('product_mismatch', 'Product Mismatch'), ('quantity_mismatch', 'Quantity Mismatch'), ('price_mismatch', 'Price Review Required'), ('closed', 'Closed')], default='sent', max_length=30),
        ),
    ]
