# Generated by Django 6.0.3 on 2026-03-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_pricehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='change_source',
            field=models.CharField(choices=[('master_inventory', 'Master Inventory Update'), ('invoice_validation', 'Invoice Validation Update')], default='master_inventory', max_length=30),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='previous_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
