# Generated by Django 6.0.3 on 2026-03-20 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_pricehistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias_name', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='inventory.product')),
            ],
            options={
                'ordering': ['alias_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'alias_name'), name='inventory_productalias_unique_product_alias')],
            },
        ),
    ]
